services:
  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: ${PROJECT_NAME}_apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  mariadb:
    image: mariadb:10.5
    container_name: ${PROJECT_NAME}_mariadb
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
